site_name: Learning Python
site_author: Wahyu Setianto
site_description: For learning python 
repo_url: https://github.com/Hyuto/learning-python
theme: 
  name: mkdocs
nav:
  - Home: index.md
  - Docs: reference.md
plugins:
  - search
  - gen-files:
      scripts:
        - utils/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            show_source: false
            merge_init_into_class: yes
            members_order: source
extra_javascript:
  - js/responsive-table.js
watch:
  - src
