name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest --cov=src/ -v --cov-report=xml:./coverage.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: learning-python
          flags: unittests
          env_vars: PYTHON
